### ISSUE TITLE
Facebook and Twitter posts doesn't return image 

### ISSUE THREAD

**Issue by Bsingh2697** [flyerhq/react-native-link-preview#15]
{"description": undefined, "image": undefined, "link": "https://www.facebook.com/100002427324091/posts/4134550663302470/", "title": "KalimpongNews Kalimpong"}

The image is always undefined no matter what fb url I pass.
I have tried Posts, Videos, images everything but this image tag is always undefined

**Comment by demchenkoalex** [comment]
Hi @Bsingh2697. To get a preview from Facebook or Twitter or probably a lot of other websites you will need a backend solution since you need a token to access Facebook/Twitter/whatever website data. Something like [this](https://www.linkpreview.net). We think our library does maximum a local library can do, but if you know how to improve it, PRs are always open :)
